// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbzQ46WuDvjDjpCCAe_jF-DcoV7oUZt7s',
    appId: '1:872930949681:web:c2dd577a7ca0d32baa7310',
    messagingSenderId: '872930949681',
    projectId: 'authfirebase2-ac051',
    authDomain: 'authfirebase2-ac051.firebaseapp.com',
    storageBucket: 'authfirebase2-ac051.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFmB5nOSj_5YftUiC4nMq7_JCuk0yuPc',
    appId: '1:872930949681:android:1a2e62cdd6bcb06caa7310',
    messagingSenderId: '872930949681',
    projectId: 'authfirebase2-ac051',
    storageBucket: 'authfirebase2-ac051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBri4hpkZ_IOffZVIBBtr7hKBrKaKrAIxY',
    appId: '1:872930949681:ios:de629f08dc4e2c86aa7310',
    messagingSenderId: '872930949681',
    projectId: 'authfirebase2-ac051',
    storageBucket: 'authfirebase2-ac051.appspot.com',
    iosBundleId: 'com.example.testApp',
  );
}
